package edu.rs.raf.userservice.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND, ACCOUNT_NOT_ACTIVATED_OR_BLOCKED, USERNAME_ALREADY_EXISTS, EMAIL_ALREADY_IN_USE, CANNOT_BAN_ADMIN, INVALID_DATE
}
